import BMW_i7 from "../../images/2024-bmw-i7.jpg";
import Allion240 from "../../images/Allion240.jpg";
import Allion260 from "../../images/allion260.jpg";
import aqua from "../../images/aqua.jpg";
import gp1 from "../../images/gp1.jpg";
import axio from "../../images/Axio.jpg";
import fd1 from "../../images/civicFD1.jpg";
import axela from "../../images/axela.jpg";

export const DEMO_DATA = [
  {
    id: 1,
    make: "Toyota",
    modle: "Allion 260 G Grade",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 7,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: Allion260,
    manufacture: "2007",
  },
  {
    id: 2,
    make: "Honda",
    modle: "Fit GP1",
    mileage: "150,000km",
    bodyType: "HatchBack",
    engine: "1.3L vtec ",
    price: "Rs. 6,500,000",
    fuel: "Hybrid",
    transsmision: "automatic",
    url: gp1,
    manufacture: "2007",
  },
  {
    id: 3,
    make: "Mazda",
    modle: "Axela",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 4,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: axela,
    manufacture: "2007",
  },
  {
    id: 4,
    make: "Honda",
    modle: "Vezel",
    mileage: "150,000km",
    bodyType: "SUV",
    engine: "1.5L VVTI",
    price: "Rs. 7,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: BMW_i7,
    manufacture: "2007",
  },
  {
    id: 5,
    make: "Toyota",
    modle: "Allion 240",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 6,000,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: Allion240,
    manufacture: "2007",
  },
  {
    id: 6,
    make: "Honda",
    modle: "Civic FD1",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.8L Vtec",
    price: "Rs. 6,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: fd1,
    manufacture: "2007",
  },
  {
    id: 7,
    make: "Honda",
    modle: "Fit GP5",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 7,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: BMW_i7,
    manufacture: "2007",
  },
  {
    id: 8,
    make: "Toyota",
    modle: "Axio",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 8,500,000",
    fuel: "Hybrid",
    transsmision: "automatic",
    url: axio,
    manufacture: "2007",
  },
  {
    id: 9,
    make: "Suzuki",
    modle: "WagonR",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 7,500,000",
    fuel: "Petrol",
    transsmision: "automatic",
    url: BMW_i7,
    manufacture: "2007",
  },
  {
    id: 10,
    make: "Toyota",
    modle: "Aqua",
    mileage: "150,000km",
    bodyType: "Sedan",
    engine: "1.5L VVTI",
    price: "Rs. 6,000,000",
    fuel: "Hybrid",
    transsmision: "automatic",
    url: aqua,
    manufacture: "2007",
  },
];
